FROM node:20-alpine AS builder
WORKDIR /app
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm ci
COPY ./frontend ./

# Принимаем PUBLIC_URL как аргумент сборки
ARG PUBLIC_URL
ENV PUBLIC_URL=$PUBLIC_URL

# Собираем проект с учетом PUBLIC_URL
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]