FROM node:22-alpine as builder
WORKDIR /app
COPY ./package.json ./package-lock.json ./
RUN npm ci
COPY ./ ./
RUN npm run build

FROM node:22-alpine as prod
WORKDIR /app
COPY --from=builder /app/package.json /app/package-lock.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
COPY ./ormconfig.prod.js ./ormconfig.prod.js
RUN npm install pm2 -g

EXPOSE 3000

CMD ["pm2-runtime", "dist/main.js"]